window.TIME_SLICE_EVENTS = [
  { year: 1900, title: "八国联军侵华，义和团运动被镇压", categories: ["公共事件"], note: "" },
  { year: 1901, title: "《辛丑条约》签订，赔款4.5亿两白银", categories: ["公共事件", "经济"], note: "" },
  { year: 1905, title: "科举制度正式废除", categories: ["公共事件", "文化结构"], note: "中国社会阶层流动通道的根本性断裂" },
  { year: 1905, title: "中国第一部电影《定军山》在北京丰泰照相馆诞生", categories: ["文化第一次"], note: "" },
  { year: 1906, title: "京汉铁路全线通车", categories: ["技术设施"], note: "南北交通动脉首次打通" },
  { year: 1908, title: "沪宁铁路全线通车", categories: ["技术设施"], note: "" },
  { year: 1909, title: "京张铁路竣工，詹天佑主持修建，中国人自行设计的第一条铁路", categories: ["技术设施"], note: "" },

  { year: 1911, title: "辛亥革命爆发，清帝退位，中华民国成立", categories: ["公共事件"], note: "" },
  { year: 1912, title: "中华书局在上海创办", categories: ["文化第一次"], note: "新式教科书开始普及" },
  { year: 1915, title: "《新青年》杂志创刊", categories: ["文化第一次"], note: "新文化运动的起点" },
  { year: 1915, title: "中国首次参加世界博览会，巴拿马太平洋万国博览会", categories: ["体育", "国际节点"], note: "" },
  { year: 1917, title: "俄国十月革命", categories: ["国际事件"], note: "后续直接影响中国共产党诞生" },
  { year: 1918, title: "中国科学社迁回国内，《科学》杂志发行", categories: ["文化结构"], note: "" },
  { year: 1919, title: "五四运动", categories: ["公共事件"], note: "" },

  { year: 1920, title: "中国首次空中航线开通，北京至天津", categories: ["技术设施"], note: "" },
  { year: 1921, title: "中国共产党成立", categories: ["公共事件"], note: "" },
  { year: 1922, title: "中国首次参加远东运动会获得足球冠军", categories: ["体育"], note: "" },
  { year: 1923, title: "京汉铁路工人大罢工，二七大罢工", categories: ["公共事件"], note: "" },
  { year: 1924, title: "黄埔军校创立", categories: ["公共事件"], note: "" },
  { year: 1926, title: "北伐战争开始", categories: ["公共事件"], note: "" },
  { year: 1928, title: "东北易帜，国民政府名义上统一全国", categories: ["公共事件"], note: "" },

  { year: 1931, title: "九一八事变，日本侵占东北", categories: ["公共事件"], note: "" },
  { year: 1932, title: "中国首次参加奥运会，刘长春单刀赴会洛杉矶", categories: ["体育里程碑"], note: "" },
  { year: 1934, title: "红军长征开始", categories: ["公共事件"], note: "" },
  { year: 1935, title: "遵义会议", categories: ["公共事件"], note: "" },
  { year: 1937, title: "卢沟桥事变，全面抗战爆发", categories: ["公共事件"], note: "" },
  { year: 1937, title: "南京大屠杀", categories: ["公共事件"], note: "" },

  { year: 1945, title: "抗战胜利，日本投降", categories: ["公共事件"], note: "" },
  { year: 1945, title: "联合国成立，中国成为常任理事国", categories: ["国际事件", "公共事件"], note: "" },
  { year: 1946, title: "解放战争全面爆发", categories: ["公共事件"], note: "" },
  { year: 1947, title: "土地改革在解放区全面推行", categories: ["经济节点"], note: "" },
  { year: 1949, title: "中华人民共和国成立", categories: ["公共事件"], note: "" },
  { year: 1949, title: "国民党迁台，两岸分治格局形成", categories: ["公共事件"], note: "" },

  { year: 1950, title: "抗美援朝战争开始", categories: ["公共事件"], note: "" },
  { year: 1950, title: "《中华人民共和国婚姻法》颁布，废除封建婚姻制度", categories: ["公共事件", "社会结构"], note: "" },
  { year: 1952, title: "土地改革在全国基本完成", categories: ["经济节点"], note: "" },
  { year: 1953, title: "第一个五年计划开始实施", categories: ["经济节点"], note: "" },
  { year: 1953, title: "全国普选首次进行", categories: ["公共事件"], note: "" },
  { year: 1954, title: "第一届全国人民代表大会召开，《中华人民共和国宪法》颁布", categories: ["公共事件"], note: "" },
  { year: 1955, title: "粮票制度开始在全国推行", categories: ["经济节点"], note: "影响几代人的日常生活" },
  { year: 1956, title: "三大改造基本完成，社会主义制度建立", categories: ["经济节点"], note: "" },
  { year: 1956, title: "国产第一辆解放牌汽车下线", categories: ["技术设施"], note: "" },
  { year: 1958, title: "中国第一台国产黑白电视机，北京牌，在天津诞生", categories: ["技术设施"], note: "" },
  { year: 1958, title: "北京电视台开播，《一口菜饼子》播出，中国第一部电视剧", categories: ["文化第一次"], note: "北京电视台为中央电视台前身" },
  { year: 1959, title: "大庆油田发现", categories: ["经济节点"], note: "" },

  { year: 1961, title: "三年自然灾害时期结束", categories: ["公共事件", "经济"], note: "" },
  { year: 1964, title: "中国第一颗原子弹爆炸成功", categories: ["公共事件", "技术设施"], note: "" },
  { year: 1966, title: "文化大革命开始", categories: ["公共事件"], note: "影响深远的十年" },
  { year: 1967, title: "中国第一颗氢弹爆炸成功", categories: ["公共事件"], note: "" },
  { year: 1968, title: "南京长江大桥建成通车", categories: ["技术设施"], note: "第一座完全由中国人设计建造的长江大桥" },

  { year: 1970, title: "中国第一颗人造卫星东方红一号发射成功", categories: ["技术设施", "公共事件"], note: "" },
  { year: 1971, title: "中国恢复在联合国的一切合法权利", categories: ["国际事件", "公共事件"], note: "" },
  { year: 1972, title: "尼克松访华，中美关系破冰", categories: ["国际事件"], note: "" },
  { year: 1973, title: "计划生育开始推行", categories: ["公共事件", "社会结构"], note: "" },
  { year: 1976, title: "唐山大地震、粉碎四人帮", categories: ["公共事件"], note: "极度密集的一年" },
  { year: 1977, title: "恢复高考", categories: ["公共事件", "教育结构"], note: "一代人命运的重新洗牌" },
  { year: 1978, title: "十一届三中全会召开，改革开放启动", categories: ["公共事件", "经济节点"], note: "整个中国社会的根本转折" },
  { year: 1978, title: "宝钢开工建设，新中国成立以来最大规模工业引进项目", categories: ["经济节点"], note: "" },
  { year: 1979, title: "中美正式建交", categories: ["国际事件"], note: "" },
  { year: 1979, title: "对越自卫反击战", categories: ["公共事件"], note: "" },
  { year: 1979, title: "改革开放后中国首次参加亚运会，金牌数第二", categories: ["体育"], note: "" },

  { year: 1980, title: "深圳、珠海、汕头、厦门经济特区正式成立", categories: ["经济节点"], note: "" },
  { year: 1981, title: "中国女排首次夺得世界杯冠军", categories: ["体育里程碑"], note: "" },
  { year: 1982, title: "家庭联产承包责任制在全国推行", categories: ["经济节点"], note: "改变了数亿农民的生产方式" },
  { year: 1983, title: "中央电视台首届春节联欢晚会播出", categories: ["文化第一次"], note: "“春晚”这个年俗的发明" },
  { year: 1984, title: "中英就香港问题签署联合声明", categories: ["公共事件"], note: "" },
  { year: 1984, title: "许海峰夺得中国奥运史上第一枚金牌", categories: ["体育里程碑"], note: "" },
  { year: 1985, title: "城市经济体制改革全面展开", categories: ["经济节点"], note: "" },
  { year: 1985, title: "中国第一个南极考察站长城站建成", categories: ["技术设施", "公共事件"], note: "" },
  { year: 1987, title: "中国第一代模拟移动电话系统在广州商用", categories: ["技术设施"], note: "手机进入中国" },
  { year: 1987, title: "中葡就澳门问题签署联合声明", categories: ["公共事件"], note: "" },
  { year: 1988, title: "海南省正式成立，成为中国最大经济特区", categories: ["经济节点"], note: "" },
  { year: 1989, title: "戈尔巴乔夫访华，中苏关系正常化", categories: ["国际事件"], note: "" },

  { year: 1990, title: "上海证券交易所成立", categories: ["经济节点"], note: "资本市场重新进入中国" },
  { year: 1990, title: "第十一届亚运会在北京举办", categories: ["体育", "公共事件"], note: "" },
  { year: 1991, title: "苏联解体，冷战结束", categories: ["国际事件"], note: "直接影响一代人的意识形态参照系" },
  { year: 1991, title: "深圳证券交易所正式开业", categories: ["经济节点"], note: "" },
  { year: 1992, title: "邓小平南方谈话，市场经济方向正式确立", categories: ["公共事件", "经济节点"], note: "" },
  { year: 1994, title: "中国全功能接入国际互联网", categories: ["技术设施"], note: "划时代的沉默背景" },
  { year: 1994, title: "人民币汇率并轨，实行有管理的浮动汇率制", categories: ["经济节点"], note: "" },
  { year: 1994, title: "三峡工程正式开工", categories: ["技术设施", "经济节点"], note: "" },
  { year: 1994, title: "中国首次引入外国电影分账大片，《亡命天涯》上映", categories: ["文化第一次"], note: "进口大片时代开启" },
  { year: 1995, title: "双休日制度开始实行", categories: ["社会结构"], note: "改变了全体中国人的生活节奏" },
  { year: 1996, title: "中国钢产量首次突破一亿吨，世界第一", categories: ["经济节点"], note: "" },
  { year: 1997, title: "香港回归", categories: ["公共事件"], note: "" },
  { year: 1997, title: "亚洲金融风暴爆发", categories: ["经济节点", "国际事件"], note: "第一次真切感受到全球化金融风险" },
  { year: 1997, title: "中国铁路第一次大面积提速", categories: ["技术设施"], note: "" },
  { year: 1998, title: "城镇住房制度改革全面启动，停止实物分房", categories: ["经济节点"], note: "商品房时代正式到来" },
  { year: 1999, title: "澳门回归", categories: ["公共事件"], note: "" },
  { year: 1999, title: "中国驻南联盟使馆被炸", categories: ["公共事件", "国际事件"], note: "" },

  { year: 2000, title: "中国第九个五年计划完成，GDP突破一万亿美元", categories: ["经济节点"], note: "" },
  { year: 2001, title: "中国正式加入世界贸易组织WTO", categories: ["经济节点", "国际事件"], note: "深度嵌入全球体系" },
  { year: 2001, title: "北京申办2008年奥运会成功", categories: ["体育", "公共事件"], note: "" },
  { year: 2003, title: "非典疫情爆发", categories: ["公共事件"], note: "第一次全民公共卫生动员" },
  { year: 2003, title: "神舟五号载人航天成功，杨利伟成为中国首位航天员", categories: ["技术设施", "公共事件"], note: "" },
  { year: 2004, title: "宪法修正案增加“公民的合法的私有财产不受侵犯”", categories: ["公共事件", "经济"], note: "" },
  { year: 2005, title: "废止农业税，存在两千多年的农业税制度终结", categories: ["经济节点", "社会结构"], note: "" },
  { year: 2006, title: "三峡大坝全线建成", categories: ["技术设施"], note: "" },
  { year: 2006, title: "青藏铁路全线通车", categories: ["技术设施"], note: "" },
  { year: 2007, title: "中国铁路第六次大面积提速，动车组首次开行", categories: ["技术设施"], note: "高铁时代前夜" },
  { year: 2007, title: "《中华人民共和国物权法》通过", categories: ["公共事件", "经济"], note: "" },
  { year: 2008, title: "南方特大雪灾", categories: ["公共事件"], note: "" },
  { year: 2008, title: "汶川大地震", categories: ["公共事件"], note: "" },
  { year: 2008, title: "北京举办第29届夏季奥运会", categories: ["体育", "公共事件"], note: "" },
  { year: 2008, title: "京津城际铁路通车，中国第一条高速铁路", categories: ["技术设施"], note: "" },
  { year: 2008, title: "全球金融危机爆发", categories: ["经济节点"], note: "" },
  { year: 2009, title: "3G牌照发放，中国进入移动互联网时代的前夜", categories: ["技术设施"], note: "" },

  { year: 2010, title: "上海举办世博会", categories: ["公共事件"], note: "" },
  { year: 2010, title: "中国GDP总量超过日本，成为世界第二大经济体", categories: ["经济节点"], note: "" },
  { year: 2011, title: "微信正式上线", categories: ["技术设施", "社会结构"], note: "通讯方式的根本改变" },
  { year: 2012, title: "中国手机网民数量首次超过PC网民", categories: ["技术设施"], note: "移动互联网正式主导" },
  { year: 2012, title: "莫言获得诺贝尔文学奖", categories: ["文化里程碑"], note: "" },
  { year: 2013, title: "4G牌照发放，移动互联网全面爆发", categories: ["技术设施"], note: "" },
  { year: 2015, title: "全面二孩政策实施", categories: ["社会结构"], note: "独生子女政策正式终结" },
  { year: 2015, title: "屠呦呦获得诺贝尔生理学或医学奖", categories: ["文化里程碑"], note: "" },
  { year: 2016, title: "全面二孩政策正式施行", categories: ["社会结构"], note: "" },
  { year: 2017, title: "雄安新区设立", categories: ["经济节点"], note: "" },
  { year: 2018, title: "中美贸易摩擦开始", categories: ["国际事件", "经济节点"], note: "" },
  { year: 2018, title: "港珠澳大桥正式通车", categories: ["技术设施"], note: "" },
  { year: 2019, title: "5G商用牌照发放", categories: ["技术设施"], note: "" },
  { year: 2019, title: "新冠疫情开始在武汉出现，后续发展为全球大流行", categories: ["公共事件"], note: "" },

  { year: 2020, title: "新冠疫情全球大流行", categories: ["公共事件"], note: "" },
  { year: 2021, title: "三孩政策正式入法", categories: ["社会结构"], note: "" },
  { year: 2022, title: "俄乌冲突爆发", categories: ["国际事件"], note: "全球地缘格局重大变化，间接影响中国" },
  { year: 2022, title: "中国人口出现近61年来首次负增长", categories: ["公共事件", "社会结构"], note: "" },
  { year: 2023, title: "ChatGPT等生成式AI产品爆发式流行", categories: ["国际事件", "技术节点"], note: "AI进入大众日常生活" },
  { year: 2024, title: "中国嫦娥六号完成世界首次月球背面采样返回", categories: ["技术节点", "公共事件"], note: "" },
  { year: 2025, title: "DeepSeek等开源生态AI大模型引发全球关注，开源生态爆发", categories: ["技术节点"], note: "" },
  { year: 2025, title: "延迟退休方案正式实施", categories: ["公共事件", "社会结构"], note: "" },
  { year: 2025, title: "中美关税战剧烈升级", categories: ["国际事件", "经济节点"], note: "" }
];
